### PR TITLE
NDK 27 & Support 16kb page size for Android15

### PR DESCRIPTION
**Pull request by brocollie08**
## Motivation

https://github.com/facebookincubator/fbjni/issues/97

## Summary

Updated ndk to 27, enabled flexible page size support

https://developer.android.com/guide/practices/page-sizes#compile-r27-higher

## Test Plan

Built locally and checked alignment via test method [here](https://developer.android.com/guide/practices/page-sizes#test) as well as `objdump` on the binary

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
@brocollie08 could you rebase? The CI should be green now

**Review by cortinico — CHANGES_REQUESTED** [review]
(see previous comment)

**Review by cortinico — APPROVED** [review]

**Comment by brocollie08** [comment]
Hey @cortinico, thanks for the quick review, anything else needed before this can go in?

**Comment by cortinico** [comment]
> Hey @cortinico, thanks for the quick review, anything else needed before this can go in?

Nope this needs to be reviewed internally and then can be merged. Can take a couple of days

**Pull request closed without merging**
