### PR TITLE
Static Improvements in Environment

### PR DESCRIPTION
**Pull request by cpsauer**
First and foremost: Thanks for a great library!

I was reading through the code after using the library for a little and noticed some stuff in Environment.(h|cpp) that looked like it must have been a holdover from a previous implementation. (Specifically: Implementation-only variable global, not static; struct containing only static functions, rather than a namespace; constructor being used only for its side effects in setting global variables.)

So, I figured I'd fix what I saw and send in a PR in case you wanted it, in the spirit of leaving things better than I found them :)  No functional changes, just a micro, static-flavored cleanup. I have tested by building and running in my project.

If you're open to it, it should be a super fast review. The PR is broken into three micro commit with messages explaining what's being fixed and why. The easiest review would be to just hop through the commits one by one, I think!

-Chris
(ex-Oculus)

### CODE REVIEW

**Comment by cpsauer** [comment]
(I've signed)

**Comment by cpsauer** [comment]
@passy, I see you're actively committing some great stuff. Any chance I could ask you for a quick review?

**Comment by cpsauer** [comment]
Thanks, Passy! Appreciate your replying, making an effort, and being open, honest and awesome.

Great question. No changes to the interface, nor behavior changes observable from outside the black box.

It's just a quick internal cleanup of some (IMO fairly clearly unintentional) stuff. Imagine you were walking through a nice building, saw some banana peels on the floor, and were like, hmm, I'm gonna clean those up before someone slips. Should be an easy review.

**Comment by cpsauer** [comment]
Friendly bump :)

**Comment by cpsauer** [comment]
@passy, another friendly bump :)

**Comment by dreiss** [comment]
I think the current EnvironmentInitializer is thread-safe (due to local static initialization being thread-safe), and the version in the PR is not.  One could argue whether there are any cases where it truly matters, but I think that is the reason for using a global.

Making g_vm static is not necessary, since putting it into an anonymous namespace already has the same effect.

As for the object -> namespace change, I believe this is an ABI-altering change that could cause issues with folks trying to upgrade, so I'd prefer to not do it unless there is some concrete benefit.  Preventing instantiation can be done by deleting constructors.

**Comment by cpsauer** [comment]
Oh, great! Thanks for giving it a read-through, David.

Thinking and replying back:
- **On the thread safety of Environment::initialize:**
I agree that static-local-init thread safety seems like a good candidate for the author's original intent. But it still seems like we're plenty thread-safe? We're just assigning a single pointer without any special alignment. And, in any case, it seems this is the kind of thing you'd set once during setup rather than calling under contention (in JNI_OnLoad or maybe VM creation outside the Android Ecosystem). Am I missing something?
One small but definite change is that, with the asserts, we're enforcing the assumption that the function isn't accidentally being called multiple times--rather than failing silently if, for example, a user tried to create multiple Java VMs.
- **On the anonymous namespace:**
Yep; you're totally right. I just missed the anonymous namespace that made `static` superfluous. I'll pop that commit.
- **On struct -> namespace:**
Hmm, I still do think the intended ABI (and API) stay the same. I did a quick test, and I'm seeing the same symbols produced by the NDK from functions in a namespace as those in a static-only struct. But maybe I'm missing something!
To explain where I was coming from on this: I'd always been taught that when I wanted to collect a list of functions under a name, they should live in a namespace, rather than a struct/class, because I didn't intend to allow instantiation. I know Google has [this as a rule](https://google.github.io/styleguide/cppguide.html#Nonmember,_Static_Member,_and_Global_Functions).

All that said, if this cleanup isn't one you guys want, just lmk and I'll close it. Not trying to push--just seeing if I could quickly give back a tiny bit by contributing potential improvements I saw while reading the code.

**Comment by cpsauer** [comment]
Still think there are some easy wins here, but I'll probably close this if I don't hear anything in the next week or so.

**Pull request closed without merging**
